@startuml

title __MODEL's Class Diagram__\n

  namespace com.news.app {
    namespace model {
      class com.news.app.model.Articles {
          - additionalProperties : Map<String, Object>
          - author : String
          - content : String
          - description : String
          - publishedAt : String
          - title : String
          - urlToImage : String
          - urlother : String
          + getAdditionalProperties()
          + getAuthor()
          + getContent()
          + getDescription()
          + getPublishedAt()
          + getSource()
          + getTitle()
          + getUrlOther()
          + getUrlToImage()
          + setAdditionalProperty()
          + setAuthor()
          + setContent()
          + setDescription()
          + setPublishedAt()
          + setSource()
          + setTitle()
          + setUrlOther()
          + setUrlToImage()
      }
    }
  }
  

  namespace com.news.app {
    namespace model {
      class com.news.app.model.Example {
          - additionalProperties : Map<String, Object>
          - status : String
          - totalResults : Integer
          + getAdditionalProperties()
          + getArticles()
          + getStatus()
          + getTotalResults()
          + setAdditionalProperty()
          + setArticles()
          + setStatus()
          + setTotalResults()
      }
    }
  }
  

  namespace com.news.app {
    namespace model {
      class com.news.app.model.Source {
          - additionalProperties : Map<String, Object>
          - id : String
          - name : String
          + getAdditionalProperties()
          + getId()
          + getName()
          + setAdditionalProperty()
          + setId()
          + setName()
      }
    }
  }
  

  com.news.app.model.Articles o-- com.news.app.model.Source : source
  com.news.app.model.Example o-- com.news.app.model.Articles : articles


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
